## Attention

In [3]:
import numpy as np
import pandas as pd

In [4]:
N, T, H = 3, 5, 4  # N : 샘플수, T : timestep, H: 벡터표현

In [5]:
# np.random.randn => 정규화된 랜덤 샘플링
hs = np.random.randn(N,T,H) # 인코더의 모든 은닉상태

In [6]:
hs

array([[[-0.57284308, -1.33752222, -0.35021034,  2.02567581],
        [-0.2156886 ,  0.1681424 , -0.13783038,  1.1055661 ],
        [-1.31612775,  0.17136102,  0.37687069, -1.19922273],
        [ 0.03008828, -0.03607446, -0.90012859,  1.400199  ],
        [-0.92616962,  0.0457527 ,  2.23683325,  1.42578893]],

       [[-1.18875535,  0.19827446, -0.15781895,  1.13989025],
        [-0.86367396,  0.9448127 , -0.17152462,  1.10260943],
        [-0.1232356 ,  0.10354317, -0.07206324, -0.57231888],
        [ 1.67507686,  2.52504416,  0.36710131, -0.71133417],
        [ 0.96670469, -0.59292298,  0.29537524,  0.68152271]],

       [[-1.72196208, -0.68685707, -0.56265988,  0.22497511],
        [-0.77009512, -1.74725145, -0.59324766, -1.31376785],
        [-2.49348862, -1.00773056,  1.39379945, -1.35765652],
        [ 0.56896492,  0.37749717, -0.09999019,  0.70029264],
        [ 1.69898362, -0.38174959, -0.27555649, -1.29879705]]])

In [7]:
h = np.random.randn(N,H) # 디코더의 모든 은닉 상태

In [8]:
h

array([[ 0.87036139,  1.15671126,  0.0602617 , -0.29102716],
       [-0.7336376 ,  0.00919988,  0.42000068,  0.31249187],
       [-0.57089904,  0.14822363,  0.73016973,  0.56077533]])

In [9]:
h.reshape(N,1,H)

array([[[ 0.87036139,  1.15671126,  0.0602617 , -0.29102716]],

       [[-0.7336376 ,  0.00919988,  0.42000068,  0.31249187]],

       [[-0.57089904,  0.14822363,  0.73016973,  0.56077533]]])

In [10]:
hr = h.reshape(N,1,H).repeat(T, axis = 1)

In [11]:
hr

array([[[ 0.87036139,  1.15671126,  0.0602617 , -0.29102716],
        [ 0.87036139,  1.15671126,  0.0602617 , -0.29102716],
        [ 0.87036139,  1.15671126,  0.0602617 , -0.29102716],
        [ 0.87036139,  1.15671126,  0.0602617 , -0.29102716],
        [ 0.87036139,  1.15671126,  0.0602617 , -0.29102716]],

       [[-0.7336376 ,  0.00919988,  0.42000068,  0.31249187],
        [-0.7336376 ,  0.00919988,  0.42000068,  0.31249187],
        [-0.7336376 ,  0.00919988,  0.42000068,  0.31249187],
        [-0.7336376 ,  0.00919988,  0.42000068,  0.31249187],
        [-0.7336376 ,  0.00919988,  0.42000068,  0.31249187]],

       [[-0.57089904,  0.14822363,  0.73016973,  0.56077533],
        [-0.57089904,  0.14822363,  0.73016973,  0.56077533],
        [-0.57089904,  0.14822363,  0.73016973,  0.56077533],
        [-0.57089904,  0.14822363,  0.73016973,  0.56077533],
        [-0.57089904,  0.14822363,  0.73016973,  0.56077533]]])

In [12]:
t1 = hr*hs
t1.shape

(3, 5, 4)

In [13]:
hr.shape, hs.shape

((3, 5, 4), (3, 5, 4))

In [14]:
t1

array([[[-4.98580500e-01, -1.54712702e+00, -2.11042708e-02,
         -5.89526669e-01],
        [-1.87727028e-01,  1.94492206e-01, -8.30589300e-03,
         -3.21749759e-01],
        [-1.14550678e+00,  1.98215225e-01,  2.27108689e-02,
          3.49006381e-01],
        [ 2.61876804e-02, -4.17277338e-02, -5.42432799e-02,
         -4.07495934e-01],
        [-8.06102282e-01,  5.29226661e-02,  1.34795377e-01,
         -4.14943297e-01]],

       [[ 8.72115621e-01,  1.82410077e-03, -6.62840668e-02,
          3.56206433e-01],
        [ 6.33623690e-01,  8.69216122e-03, -7.20404569e-02,
          3.44556479e-01],
        [ 9.04102701e-02,  9.52584484e-04, -3.02666110e-02,
         -1.78844997e-01],
        [-1.22889937e+00,  2.32300972e-02,  1.54182798e-01,
         -2.22286142e-01],
        [-7.09210910e-01, -5.45481884e-03,  1.24057802e-01,
          2.12970304e-01]],

       [[ 9.83066502e-01, -1.01808446e-01, -4.10837215e-01,
          1.26160493e-01],
        [ 4.39646568e-01, -2.58983947e-

In [15]:
score = np.sum(t1, axis = 2)
print(score)

[[-2.65633846 -0.32329047 -0.57557431 -0.47727927 -1.03332754]
 [ 1.16386209  0.91483187 -0.11774875 -1.27377261 -0.37763762]
 [ 0.59658133 -0.98923746  1.53053067  0.05082949 -1.95606878]]


In [16]:
def softmax(x):
    if x.ndim == 2:
        x = x - x.max(axis=1, keepdims=True)
        x = np.exp(x)
        x /= x.sum(axis=1, keepdims=True)
    elif x.ndim == 1:
        x = x - np.max(x)
        x = np.exp(x) / np.sum(np.exp(x))

    return x

class Softmax:
    def init(self):
        self.params, self.grads = [], []
        self.out = None

    def forward(self, x):
        self.out = softmax(x)
        return self.out

    def backward(self, dout):
        dx = self.out * dout
        sumdx = np.sum(dx, axis=1, keepdims=True)
        dx -= self.out * sumdx
        return dx

In [17]:
a = Softmax().forward(score)

In [18]:
# 확인
a.sum(axis =1)

array([1., 1., 1.])

In [19]:
ar = a.reshape(N,T,1).repeat(H, axis = 2)

In [20]:
ar.shape

(3, 5, 4)

In [28]:
ar

array([[[0.03009671, 0.03009671, 0.03009671, 0.03009671],
        [0.31027654, 0.31027654, 0.31027654, 0.31027654],
        [0.24109237, 0.24109237, 0.24109237, 0.24109237],
        [0.26599438, 0.26599438, 0.26599438, 0.26599438],
        [0.15254001, 0.15254001, 0.15254001, 0.15254001]],

       [[0.42398513, 0.42398513, 0.42398513, 0.42398513],
        [0.33052033, 0.33052033, 0.33052033, 0.33052033],
        [0.11769394, 0.11769394, 0.11769394, 0.11769394],
        [0.03704242, 0.03704242, 0.03704242, 0.03704242],
        [0.09075819, 0.09075819, 0.09075819, 0.09075819]],

       [[0.22693235, 0.22693235, 0.22693235, 0.22693235],
        [0.04647122, 0.04647122, 0.04647122, 0.04647122],
        [0.57743811, 0.57743811, 0.57743811, 0.57743811],
        [0.13148596, 0.13148596, 0.13148596, 0.13148596],
        [0.01767236, 0.01767236, 0.01767236, 0.01767236]]])

In [21]:
hs.shape

(3, 5, 4)

In [23]:
t = hs * ar
t.shape

(3, 5, 4)

In [25]:
c = np.sum(t, axis=1)
c.shape

(3, 4)

In [26]:
c

array([[-0.53474676,  0.05061297,  0.13933235,  0.70480887],
       [-0.65419521,  0.44825276, -0.09168063,  0.81587711],
       [-1.76155557, -0.77607986,  0.63156122, -0.72483504]])